# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-bootstrap
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: TF Cloud Builder
  source:
    repo: https://github.com/terraform-google-modules/terraform-google-bootstrap.git
    sourceType: git
  version: 6.4.0
  actuationTool:
    type: Terraform
    version: '>=0.13.0'
  examples:
  - name: cloudbuild_enabled
    location: examples/cloudbuild_enabled
  - name: simple
    location: examples/simple
  - name: simple-folder
    location: examples/simple-folder
  - name: tf_cloudbuild_builder_simple
    location: examples/tf_cloudbuild_builder_simple
  - name: tf_cloudbuild_source_simple
    location: examples/tf_cloudbuild_source_simple
  - name: tf_cloudbuild_workspace_simple
    location: examples/tf_cloudbuild_workspace_simple
  variables:
  - name: bucket_name
    description: Custom bucket name for Cloud Build logs.
    type: string
    default: ""
    required: false
  - name: cb_logs_bucket_force_destroy
    description: When deleting the bucket for storing CloudBuild logs, this boolean option will delete all contained objects. If false, Terraform will fail to delete buckets which contain objects.
    type: bool
    default: false
    required: false
  - name: cloudbuild_sa
    description: Custom SA email to be used by the CloudBuild trigger. Defaults to being created if empty.
    type: string
    default: ""
    required: false
  - name: dockerfile_repo_dir
    description: The directory inside the repo where the Dockerfile is located. If empty defaults to repo root.
    type: string
    default: ""
    required: false
  - name: dockerfile_repo_ref
    description: The branch or tag to use. Use refs/heads/branchname for branches or refs/tags/tagname for tags.
    type: string
    default: refs/heads/main
    required: false
  - name: dockerfile_repo_type
    description: Type of repo
    type: string
    default: CLOUD_SOURCE_REPOSITORIES
    required: false
  - name: dockerfile_repo_uri
    description: The URI of the repo where the Dockerfile for Terraform builder is stored
    type: string
    required: true
  - name: enable_worker_pool
    description: Set to true to use a private worker pool in the Cloud Build Trigger.
    type: bool
    default: false
    required: false
  - name: gar_repo_location
    description: Name of the location for the Google Artifact Repository.
    type: string
    default: us
    required: false
  - name: gar_repo_name
    description: Name of the Google Artifact Repository where the Terraform builder images are stored.
    type: string
    default: tf-runners
    required: false
  - name: image_name
    description: Name of the image for the Terraform builder.
    type: string
    default: terraform
    required: false
  - name: project_id
    description: GCP project for Cloud Build trigger,workflow and scheduler.
    type: string
    required: true
  - name: terraform_version
    description: The initial terraform version in semantic version format.
    type: string
    default: 1.1.0
    required: false
  - name: trigger_location
    description: Location of the Cloud Build trigger building the Terraform builder. If using private pools should be the same location as the pool.
    type: string
    default: global
    required: false
  - name: trigger_name
    description: Name of the Cloud Build trigger building the Terraform builder.
    type: string
    default: tf-cloud-builder-build
    required: false
  - name: worker_pool_id
    description: 'Custom private worker pool ID. Format: ''projects/PROJECT_ID/locations/REGION/workerPools/PRIVATE_POOL_ID''.'
    type: string
    default: ""
    required: false
  - name: workflow_name
    description: Name of the workflow managing builds.
    type: string
    default: terraform-runner-workflow
    required: false
  - name: workflow_region
    description: The region of the workflow.
    type: string
    default: us-central1
    required: false
  - name: workflow_sa
    description: Custom SA email to be used by the workflow. Defaults to being created if empty.
    type: string
    default: ""
    required: false
  - name: workflow_schedule
    description: The workflow frequency, in cron syntax
    type: string
    default: 0 8 * * *
    required: false
  outputs:
  - name: artifact_repo
    description: GAR Repo created to store TF Cloud Builder images
  - name: cloudbuild_sa
    description: SA used by Cloud Build trigger
  - name: cloudbuild_trigger_id
    description: Trigger used for building new TF Builder
  - name: scheduler_id
    description: Scheduler ID for periodically triggering TF Builder build Workflow
  - name: workflow_id
    description: Workflow ID for triggering new TF Builder build
  - name: workflow_sa
    description: SA used by Workflow for triggering new TF Builder build
  roles:
  - level: Project
    roles:
    - roles/owner
  - level: Project
    roles:
    - roles/billing.user
    - roles/resourcemanager.organizationAdmin
    - roles/orgpolicy.policyAdmin
    - roles/resourcemanager.projectCreator
  services:
  - cloudresourcemanager.googleapis.com
  - cloudbilling.googleapis.com
  - iam.googleapis.com
  - storage-api.googleapis.com
  - serviceusage.googleapis.com
  - cloudbuild.googleapis.com
  - sourcerepo.googleapis.com
  - cloudkms.googleapis.com
  - artifactregistry.googleapis.com
  - workflows.googleapis.com
  - cloudscheduler.googleapis.com
